name: Build and Push Docker Image

on:
  push:
    branches:
      - '*'
  pull-request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black
    
    - name: Lint code
      run: |
        flake8 .
        black --check
    
    - name: CodeQL Analysis
      uses: github/codeql-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/django_inventory_system:${{ github.event.pull_request.head.ref }}

    - name: Run tests
      run: |
        docker run --rm ${{ secrets.DOCKER_USERNAME }}/django_inventory_system:${{ github.event.pull_request.head.ref }} python manage.py test