# Generated by Django 5.0.6 on 2024-05-27 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Administrator", "Administrator"),
                    ("Inventory Manager", "Inventory Manager"),
                    ("Warehouse Staff", "Warehouse Staff"),
                    ("Purchasing Manager", "Purchasing Manager"),
                    ("Sales Manager", "Sales Manager"),
                    (
                        "Customer Service Representative",
                        "Customer Service Representative",
                    ),
                    ("Accountant", "Accountant"),
                    ("Auditor", "Auditor"),
                    ("System User", "System User"),
                    ("Customer", "Customer"),
                    ("Standard User", "Standard User"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("location", models.CharField(max_length=255)),
                (
                    "participants",
                    models.ManyToManyField(related_name="events", to="inventory.user"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("due_date", models.DateField()),
                ("completed", models.BooleanField(default=False)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inventory.user"
                    ),
                ),
            ],
        ),
    ]
