# Generated by Django 5.0.6 on 2024-06-02 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_emailattachment_internaluser_alter_order_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Accountant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accountant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("view_inventory_report", "Can view inventory reports"),
                    ("adjust_inventory_levels", "Can adjust inventory levels"),
                    ("audit_inventory", "Can perform audit of inventory"),
                    ("manage_suppliers", "Can manage suppliers"),
                    ("manage_purchasing", "Can manage purchasing of new inventory"),
                    ("add_supplier", "Can add a new supplier"),
                    ("update_supplier", "Can update existing supplier information"),
                    ("delete_supplier", "Can delete a supplier"),
                    ("manage_pricing", "Can set and change prices for products"),
                    ("set_discounts", "Can set discounts on products"),
                    ("create_invoice", "Can create invoices for transactions"),
                    ("manage_returns", "Can manage product returns"),
                    ("issue_refunds", "Can issue refunds for returns"),
                    ("record_payment", "Can record a payment to a supplier"),
                    ("view_payments", "Can view the payments history"),
                    ("set_tax_rates", "Can set tax rates for products"),
                    ("calculate_taxes", "Can calculate taxes based on set rates"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SalesTransaction",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField()),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(max_length=50)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
            ],
        ),
    ]
